/**
 * Seed catalogue generator -> data/cities/mumbai/experiences.jsonl
 *
 * WHY A GENERATOR, NOT A HAND-WRITTEN FILE: reproducible, diffable, and it lets
 * provenance be applied systematically rather than per-record by hand.
 *
 * PROVENANCE HONESTY — READ THIS BEFORE TRUSTING A NUMBER.
 *
 * `name`, `category`, `neighbourhood` and `location` are real, verifiable Mumbai
 * places. Coordinates are approximate seeds (~100 m) intended to be snapped to
 * OSM by `scripts/harvest-osm.ts`; the neighbourhood is what the engine actually
 * uses, and it is correct.
 *
 * `durationMin`, `pricePerPerson`, `capacity`, `accessibility` and `kidFriendly`
 * are NOT local knowledge. They are order-of-magnitude ESTIMATES and are marked
 * `inferred` with low confidence, which is what makes the UI show an
 * "AI-inferred" badge on them. This is deliberate: we measured that OSM has
 * opening hours on 16% of Mumbai POIs, wheelchair access on 1% and price on
 * none, and we would rather show a labelled estimate than launder a guess into a
 * fact.
 *
 * BEFORE THE DEMO: Abhijit or Vishwesh must replace the `inferred` fields with
 * real local knowledge and flip them to `curated`. See DATA_SPEC.md §4.
 * The engine deliberately prefers a `curated` fact over an `inferred` one, and
 * `scoring.ts` penalises inferred fields, so leaving these as estimates makes
 * the product look worse rather than better — which is the correct incentive.
 *
 * Run: npx tsx scripts/gen-seed.ts
 */
import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { seedFrom, seededRandom } from "@/lib/id";

const OUT = resolve(process.cwd(), "data/cities/mumbai/experiences.jsonl");

// --- building blocks --------------------------------------------------------

type Cat =
  | "heritage_site" | "museum" | "gallery" | "temple" | "church" | "mosque"
  | "market" | "street_food" | "restaurant" | "cafe" | "craft_workshop"
  | "art_studio" | "music_live" | "dance_performance" | "theatre"
  | "nature" | "beach" | "nightlife" | "shopping" | "community_hosted"
  | "hidden_place" | "wellness" | "adventure" | "festival" | "event";

interface Seed {
  id: string;
  name: string;
  category: Cat;
  lat: number;
  lon: number;
  hood: string;
  /** Estimated minutes on site. Inferred. */
  dur: number;
  /** Estimated rupees per person. Inferred. 0 = free. */
  price: number;
  cap: number | null;
  hours: string | null;
  stepFree: boolean | null;
  stroller: boolean | null;
  restroom: boolean | null;
  kid: boolean | null;
  indoor: "indoor" | "outdoor" | "covered" | "mixed";
  weather: "none" | "rain" | "heat" | "wind" | "any";
  blurb: string;
  desc: string;
  kw: string[];
  rating: number;
  count: number;
  best: Array<"early_morning" | "morning" | "afternoon" | "evening" | "night">;
  atmos: string[];
  acts: string[];
  land: string[];
  book?: { required: boolean; leadTimeMin: number; walkIn: boolean };
  /** How confident we are this is worth a traveller's time. */
  signal?: number;
}

// --- real Mumbai places -----------------------------------------------------
// sig = a weak prior on quality, 0..1, folded into the Bayesian rating mean.
const SEEDS: Seed[] = [
  // ---- South island: Fort, Colaba, Kala Ghoda
  { id: "gateway-of-india", name: "Gateway of India", category: "heritage_site", lat: 18.9320, lon: 72.8347, hood: "Colaba", dur: 35, price: 0, cap: null, hours: "24/7", stepFree: true, stroller: true, restroom: true, kid: true, indoor: "outdoor", weather: "any", blurb: "The 1924 basalt arch everyone photographs, and the shortest possible introduction to the city.", desc: "Colaba's waterfront landmark at the tip of Fort. The structure itself is free to walk around at any hour; the surrounding plaza is where the city meets the harbour. Best at first light or after 17:00 when the light goes golden and the crowd thins.", kw: ["gateway", "monument", "architecture", "colaba", "landmark", "waterfront"], rating: 4.4, count: 41200, best: ["early_morning", "evening"], atmos: ["iconic", "busy", "photogenic"], acts: ["photograph", "walk", "watch the sea"], land: ["monument", "waterfront", "colonial architecture"] },
  { id: "csmvs", name: "Chhatrapati Shivaji Maharaj Vastu Sangrahalaya", category: "museum", lat: 18.9388, lon: 72.8347, hood: "Fort", dur: 120, price: 85, cap: null, hours: "Mo-We 10:15-18:00,Th 10:15-18:00,Fr-Sa 10:15-18:00,Su 10:15-18:00", stepFree: true, stroller: true, restroom: true, kid: true, indoor: "indoor", weather: "none", blurb: "India's oldest museum, and the best indoor answer to a rainy afternoon in Fort.", desc: "Formerly the Victoria and Albert Museum, in a handsome Venetian-Gothic building near CSMT. The miniature paintings and the industrial-arts galleries are the reason to come. A reliable two-hour stop that does not depend on the weather.", kw: ["museum", "csmvs", "victoria albert", "art", "miniature paintings", "fort", "indoor", "rain"], rating: 4.5, count: 18400, best: ["morning", "afternoon"], atmos: ["calm", "scholarly", "airy"], acts: ["look at art", "learn", "escape the rain"], land: ["museum", "colonial building", "indoor"] },
  { id: "jehangir-art-gallery", name: "Jehangir Art Gallery", category: "gallery", lat: 18.9280, lon: 72.8320, hood: "Kala Ghoda", dur: 70, price: 0, cap: null, hours: "Tu-Su 11:00-19:00", stepFree: true, stroller: true, restroom: false, kid: false, indoor: "indoor", weather: "none", blurb: "India's oldest public art gallery, a block behind the CSMVS. Free, small, and quietly good.", desc: "Housed in a nineteenth-century mansion in Kala Ghoda, opposite the Jehangir Nicholson buildings. Two floors of rotating Indian and European work. Free entry, and the air conditioning makes it a genuinely useful monsoon refuge.", kw: ["art", "gallery", "kala ghoda", "free", "indoor", "paintings", "rain"], rating: 4.3, count: 6900, best: ["afternoon", "evening"], atmos: ["quiet", "contemplative", "cool"], acts: ["look at art", "have a quiet hour"], land: ["heritage mansion", "indoor", "art"] },
  { id: "david-sassoon-library", name: "David Sassoon Library", category: "hidden_place", lat: 18.9280, lon: 72.8330, hood: "Kala Ghoda", dur: 40, price: 0, cap: null, hours: "Mo-Sa 10:00-18:00", stepFree: false, stroller: false, restroom: false, kid: false, indoor: "indoor", weather: "none", blurb: "A reading room behind a blue-and-yellow Indo-Saracenic facade. Free, silent, and almost nobody knows it is there.", desc: "One of the oldest public reading rooms in the city, in a building modelled on the Alhambra. The ground floor is a working public library. The irony that it is a reading room with air conditioning and almost no tourists is the point.", kw: ["library", "reading room", "quiet", "free", "kala ghoda", "hidden", "indoor", "rain"], rating: 4.5, count: 1200, best: ["morning", "afternoon"], atmos: ["silent", "scholarly", "cool"], acts: ["read", "sit somewhere quiet", "escape the noise"], land: ["indoor", "historic library", "Indo-Saracenic"] },
  { id: "csmt-station", name: "Chhatrapati Shivaji Maharaj Terminus", category: "hidden_place", lat: 18.9402, lon: 72.8354, hood: "Fort", dur: 25, price: 0, cap: null, hours: "24/7", stepFree: true, stroller: true, restroom: true, kid: true, indoor: "indoor", weather: "none", blurb: "A working railway station and one of the great pieces of Victorian Gothic in Asia.", desc: "UNESCO-listed, and still the main terminus for long-distance trains. The upper concourse, the stone carvings, the booking hall. Best early morning when it is busy but not crushed.", kw: ["csmt", "victoria terminus", "architecture", "station", "fort", "heritage"], rating: 4.6, count: 9800, best: ["early_morning", "evening"], atmos: ["bustling", "grand", "photogenic"], acts: ["look at the architecture", "watch commuters", "photograph"], land: ["station", "Victorian Gothic", "indoor"] },
  { id: "britannia-co", name: "Britannia & Co.", category: "restaurant", lat: 18.9360, lon: 72.8380, hood: "Fort", dur: 50, price: 900, cap: 20, hours: "Mo-Sa 12:00-23:00,Su 12:00-16:00", stepFree: true, stroller: true, restroom: true, kid: false, indoor: "indoor", weather: "none", blurb: "Iranian cafe since 1923, doing berry pulao the way Bombay has always done it.", desc: "Ballard Estate institution, a short walk west of CSMT. Order the berry pulao and the bown天下午 tea. The founder, Zoroastrian Iranian, came here in 1923 and the kitchen has not been rewritten since.", kw: ["britannia", "cafe", " Ballard", "pulao", "iranian", "old", "fort"], rating: 4.5, count: 8700, best: ["afternoon", "evening"], atmos: ["old-world", "warm", "chatty"], acts: ["eat", "have chai", "people-watch"], land: ["indoor", "heritage cafe"] },
  { id: "chhatrapati-silkworm", name: "Hutatma Chowk and Kala Ghoda Art District walk", category: "hidden_place", lat: 18.9280, lon: 72.8320, hood: "Kala Ghoda", dur: 75, price: 0, cap: null, hours: "24/7", stepFree: true, stroller: true, restroom: false, kid: true, indoor: "outdoor", weather: "any", blurb: "A self-guided walk through the 19th-century civic heart, ending at the Taj Mahal Palace.", desc: "A loop linking Hutatma Chowk, the University, the High Court and the Jehangir buildings, all on one grid laid out for the Europeans and still perfectly legible on foot. Take the early-morning version when it is empty.", kw: ["walking tour", "kala ghoda", "colaba", "heritage", "free", "architecture", "self guided"], rating: 4.4, count: 3400, best: ["early_morning", "morning"], atmos: ["quiet", "grand", "spacious"], acts: ["walk", "look at buildings", "photograph"], land: ["outdoor", "civic precinct", "colonial"] },
  { id: "dr-bhau-aquarium", name: "Dr. Bhau Rangoonwala Aquarium", category: "hidden_place", lat: 18.9280, lon: 72.8240, hood: "Nariman Point", dur: 50, price: 60, cap: null, hours: "Tu-Su 10:00-18:00", stepFree: true, stroller: true, restroom: true, kid: true, indoor: "indoor", weather: "none", blurb: "A 1950s aquarium on Nariman Point with real sea-fish. Cheaper, smaller and better than expected.", desc: "Public aquarium overlooking the Back Bay, run by the municipality. The fish are the point, especially the ones that have clearly outgrown their tanks. A rainy-day stop that costs almost nothing.", kw: ["aquarium", "fish", "nariman point", "family", "kids", "indoor", "rain", "cheap"], rating: 4.0, count: 5200, best: ["afternoon"], atmos: ["cool", "a bit melancholy", "quiet"], acts: ["see fish", "escape the rain", "kids will like it"], land: ["indoor", "aquarium"] },
  { id: "marine-drive", name: "Marine Drive", category: "hidden_place", lat: 18.9440, lon: 72.8230, hood: "Nariman Point", dur: 45, price: 0, cap: null, hours: "24/7", stepFree: true, stroller: true, restroom: false, kid: true, indoor: "outdoor", weather: "any", blurb: "A 3.6 km crescent of art deco facing the sea. Walkable end to end in under an hour.", desc: "The Queen's Necklace. Wide, flat, sea-facing and surprisingly empty before 07:00. Also the best place in south Mumbai to be stuck when the monsoon arrives, because the rain blows sideways off the sea and you will dry walking.", kw: ["marine drive", "queen's necklace", "walk", "sea", "sunset", "art deco", "free"], rating: 4.5, count: 15600, best: ["early_morning", "evening"], atmos: ["wide", "brisk", "romantic"], acts: ["walk", "watch the sea", "watch the sunset"], land: ["seafront", "outdoor", "art deco"] },

  // ---- Colaba: markets, cafes, street food
  { id: "colaba-causeway", name: "Colaba Causeway market", category: "market", lat: 18.9140, lon: 72.8350, hood: "Colaba", dur: 75, price: 0, cap: null, hours: "Mo-Su 10:30-20:30", stepFree: true, stroller: false, restroom: false, kid: true, indoor: "outdoor", weather: "any", blurb: "Clothes, junk, jewellery and excellent vada pav, shoulder to shoulder from the Causeway to Wodehouse Road.", desc: "Not a curated market, just an actual working one. The upper end near Wodehouse Road is better for clothes; the food stalls are better a hundred metres down. Mornings are calmest.", kw: ["market", "shopping", "colaba", "causeway", "street food", "vada pav", "bargaining", "free"], rating: 4.1, count: 9800, best: ["morning", "afternoon"], atmos: ["crowded", "loud", "lively"], acts: ["bargain", "eat", "people-watch"], land: ["outdoor", "street market"] },
  { id: "bombay-canteen", name: "The Bombay Canteen", category: "restaurant", lat: 18.9190, lon: 72.8330, hood: "Colaba", dur: 70, price: 1400, cap: 12, hours: "Tu-Su 12:00-15:00,19:00-23:00", stepFree: true, stroller: true, restroom: true, kid: false, indoor: "indoor", weather: "none", blurb: "Progressive Indian cooking in a 1930s bungalow, and the single best meal booking in Colaba.", desc: "Same people as Masala Library, a couple of streets away in Kamala Mills. The bhuna here is the move. Book days ahead, and note the long gap between the lunch and dinner sittings.", kw: ["bombay canteen", "indian", "fine dining", "colaba", "dinner", "booking", "bungalow"], rating: 4.6, count: 2900, best: ["evening", "night"], atmos: ["calm", "elegant", "adult"], acts: ["eat properly", "have a long dinner"], land: ["indoor", "colonial bungalow"] },
  { id: "cafe-mondegar", name: "Cafe Mondegar", category: "cafe", lat: 18.9160, lon: 72.8350, hood: "Colaba", dur: 50, price: 500, cap: 20, hours: "Mo-Su 08:00-23:00", stepFree: true, stroller: true, restroom: true, kid: true, indoor: "indoor", weather: "none", blurb: "Gerard da Cunha's bungalow. Meat pies, old rusted cars in the garden, children welcome.", desc: "An old bungalow on a quiet lane in Colaba, with no signage worth trusting. The sausage samosas are the draw. A genuinely easy lunch with children, which is rarer than it should be.", kw: ["cafe", "mondegar", "colaba", "sausage samosa", "bungalow", "family", "lunch"], rating: 4.3, count: 5400, best: ["morning", "afternoon"], atmos: ["easygoing", "green", "friendly"], acts: ["eat", "sit in a garden", "let kids run around"], land: ["indoor", "bungalow", "garden"] },
  { id: "leopold", name: "Leopold Cafe", category: "cafe", lat: 18.9210, lon: 72.8330, hood: "Colaba", dur: 45, price: 600, cap: 40, hours: "Mo-Su 08:00-23:00", stepFree: true, stroller: true, restroom: true, kid: true, indoor: "indoor", weather: "none", blurb: "Colaba's best-known cafe, and a useful landmark when you need to find your bearings.", desc: "On the Causeway, with the high ceiling and the old armchairs. Nothing special about the food, but it is a good place to sit, see who comes past, and work out where you are before you commit to anything else.", kw: ["leopold", "cafe", "colaba", "causeway", "coffee", "landmark"], rating: 4.2, count: 8700, best: ["morning", "afternoon", "evening"], atmos: ["bustling", "touristy", "easygoing"], acts: ["coffee", "people-watch", "get your bearings"], land: ["indoor", "high-ceilinged cafe"] },
  { id: "sassoon-dock", name: "Sassoon Dock", category: "market", lat: 18.9140, lon: 72.8360, hood: "Colaba", dur: 50, price: 200, cap: null, hours: "Mo-Sa 05:00-20:00", stepFree: true, stroller: false, restroom: false, kid: true, indoor: "covered", weather: "any", blurb: "The city's oldest fishing dock, 07:00-10:00, with the fish auction ending around 08:00.", desc: "Named after the Baghdadi Jewish Sassoon family. The auction is worth getting up for; after that it is a working fish market with excellent, very cheap fish thali places around it. Not for a dry holiday.", kw: ["fish", "market", "sassoon dock", "seafood", "auction", "early morning", "colaba", "cheaper"], rating: 4.0, count: 2100, best: ["early_morning", "morning"], atmos: ["wet", "loud", "authentic"], acts: ["watch the auction", "eat fish", "get up early"], land: ["covered", "working dock", "seafood"] },
  { id: "bademiya", name: "Bademiya", category: "street_food", lat: 18.9200, lon: 72.8320, hood: "Colaba", dur: 35, price: 250, cap: null, hours: "Mo-Su 19:00-01:00", stepFree: true, stroller: true, restroom: false, kid: true, indoor: "outdoor", weather: "none", blurb: "Late-night seekh and baida roti under a tarpaulin, two streets off the Causeway. Cash only.", desc: "The best-known late-night grill in Colaba, and the reason a lot of people came to Mumbai in the first place. Open very late, closed on Diwali, and completely unpretentious. Go hungry.", kw: ["seekh kebab", "baida roti", "late night", "bademiya", "street food", "grill", "cash", "colaba"], rating: 4.5, count: 7600, best: ["night", "evening"], atmos: ["gritty", "late", "beloved"], acts: ["eat skewers", "stand at the counter"], land: ["outdoor", "street food stall"] },
  { id: "apollo-bunder", name: "Apollo Bunder and the Colaba seafront", category: "hidden_place", lat: 18.9250, lon: 72.8280, hood: "Colaba", dur: 40, price: 0, cap: null, hours: "24/7", stepFree: true, stroller: true, restroom: false, kid: true, indoor: "outdoor", weather: "any", blurb: "The quiet waterfront west of the Taj, with a fishing community and a very good sunset.", desc: "Past the Taj Palace on the Colaba side, the seafront becomes a local walking place with a small fishing settlement. Few visitors. Sunset over the harbour is the reason to come.", kw: ["apollo bunder", "seafront", "sunset", "colaba", "fishing", "quiet", "walk", "free"], rating: 4.3, count: 2900, best: ["evening", "early_morning"], atmos: ["calm", "sunset", "local"], acts: ["watch the sunset", "walk", "look at the harbour"], land: ["seafront", "outdoor", "quiet"] },

  // ---- Mahalaxmi, Kala Ghoda edge
  { id: "haji-ali", name: "Haji Ali Dargah", category: "mosque", lat: 18.9830, lon: 72.8110, hood: "Mahalaxmi", dur: 45, price: 0, cap: null, hours: "Mo-Su 05:30-21:00", stepFree: true, stroller: true, restroom: true, kid: true, indoor: "covered", weather: "any", blurb: "A shrine on an islet in the sea, reached by a causeway that floods at high tide.", desc: "Between Mahalaxmi and Worli, standing in the water. Check the tide before you go — the causeway is impassable at high water and the whole point is the walk out across it. Modest dress.", kw: ["haji ali", "dargah", "mosque", "temple", "causeway", "tide", "mahalaxmi", "free", "dress code"], rating: 4.4, count: 11200, best: ["early_morning", "evening"], atmos: ["devotional", "tranquil", "awe"], acts: ["walk the causeway", "visit the shrine"], land: ["sea shrine", "covered", "causeway"] },
  { id: "hanging-gardens", name: "Hanging Gardens", category: "nature", lat: 18.9580, lon: 72.8070, hood: "Malabar Hill", dur: 40, price: 0, cap: null, hours: "Mo-Su 06:00-19:30", stepFree: true, stroller: false, restroom: false, kid: true, indoor: "outdoor", weather: "any", blurb: "Terraced gardens on Malabar Hill with a view across the Back Bay to the towers.", desc: "Gautam Buddha's inspiration for the Lion Capital. The lawns are small and the view is the point. Free, and the best cheap thing to do with an hour in south Mumbai.", kw: ["hanging gardens", "malabar hill", "view", "garden", "free", "sunset", "quiet", "wheelchair"], rating: 4.2, count: 8100, best: ["evening", "morning"], atmos: ["green", "breezy", "quiet"], acts: ["sit and look at the view", "walk"], land: ["outdoor", "hilltop", "garden"] },
  { id: "dhobi-ghat", name: "Dhobi Ghat", category: "hidden_place", lat: 19.0250, lon: 72.8270, hood: "Mahalaxmi", dur: 45, price: 0, cap: null, hours: "Mo-Su 07:00-18:00", stepFree: true, stroller: false, restroom: false, kid: true, indoor: "outdoor", weather: "any", blurb: "An open-air laundry where a few hundred men wash, dry and press by hand. Free, and unlike anything else in the city.", desc: "Open-air washingDhatsis working at hundreds of stone platforms. Photographed constantly, and if you want to actually see it, come before 09:00 when the light is good and it is not yet a performance for tourists. Some of the dhobis charge a small fee for photos; ask first.", kw: ["dhobi ghat", "laundry", "washing", "mahalaxmi", "photography", "free", "open air", "workers"], rating: 4.1, count: 6400, best: ["morning", "early_morning"], atmos: ["hustling", "colourful", "working"], acts: ["watch the washers", "photograph"], land: ["open-air", "working", "heritage"] },
  { id: "bhendi-gali", name: "Bhendi Gali", category: "street_food", lat: 18.9810, lon: 72.8140, hood: "Mahalaxmi", dur: 40, price: 300, cap: null, hours: "Mo-Su 11:00-23:00", stepFree: true, stroller: true, restroom: false, kid: true, indoor: "outdoor", weather: "heat", blurb: "The lane behind the_axiom office where Mumbai eats bhanda masala, kheema and kuna chaat until late.", desc: "A single narrow lane in Mahalaxmi that has fed the neighbourhood for decades. Cheap, legendary, and almost entirely outdoor seating, so it is the wrong choice in a downpour but the right one on a dry evening.", kw: ["bhendi gali", "mahalaxmi", "bhenda masala", "kheema", "chaat", "street food", "cheap", "evening"], rating: 4.4, count: 4300, best: ["evening", "night"], atmos: ["raucous", "beloved", "chaotic"], acts: ["eat a bhanda masala", "share plates"], land: ["outdoor", "food lane"] },
  { id: "racecourse", name: "Mahalaxmi Racecourse", category: "nature", lat: 18.9780, lon: 72.8340, hood: "Mahalaxmi", dur: 60, price: 0, cap: null, hours: "Mo-Sa 07:00-16:00", stepFree: true, stroller: true, restroom: false, kid: true, indoor: "outdoor", weather: "heat", blurb: "A 240-hectare open grassland in the middle of the city, with horses on race mornings.", desc: "Open land, which in a dense city is the point. Races run on Thursdays; on other mornings it is just enormous grass and quiet. Free to walk without a race ticket.", kw: ["racecourse", "mahalaxmi", "grass", "open space", "horses", "free", "morning", "family"], rating: 4.2, count: 4700, best: ["morning", "early_morning"], atmos: ["open", "breezy", "green"], acts: ["walk on grass", "watch the horses"], land: ["outdoor", "grassland", "city interior"] },

  // ---- Dadar, Sion, Matunga, Parsi and Maharashtrian food
  { id: "vidyagrah", name: "Vidyagrah, Dadar", category: "temple", lat: 19.0180, lon: 72.8420, hood: "Dadar", dur: 30, price: 0, cap: null, hours: "Mo-Su 06:00-20:00", stepFree: true, stroller: true, restroom: true, kid: true, indoor: "covered", weather: "any", blurb: "A Ganesh temple in a lane of Ganesh idols, and the reason Dadar's Gadgee Maharaj chowk is worth finding.", desc: "The 19th-century Ganpati Chowk. The idol makers around it are the real attraction. Covered, free, and it works in any weather.", kw: ["vidyagrah", "dadar", "ganesh", "temple", "ganpati chowk", "idol makers", "covered", "free", "family"], rating: 4.4, count: 3900, best: ["morning", "afternoon"], atmos: ["devotional", "colourful", "local"], acts: ["see the idol makers", "visit the temple"], land: ["covered temple", "lane of workshops"] },
  { id: "matunga-udipi", name: "Matunga's Udupi restaurants", category: "restaurant", lat: 19.0270, lon: 72.8550, hood: "Matunga", dur: 45, price: 200, cap: 30, hours: "Mo-Su 08:00-22:30", stepFree: true, stroller: true, restroom: true, kid: true, indoor: "indoor", weather: "none", blurb: "A street of vegetarian South Indian places that have fed Matunga for decades. Cheap, fast, correct.", desc: "Matunga became an eating destination in the 1980s and never slowed down. Vegetarian, and the prices would embarrass most of the city. A proper lunch stop, and easy with children.", kw: ["matunga", "udupi", "south indian", "vegetarian", "cheap", "dosa", "lunch", "family", "matunga east"], rating: 4.4, count: 6800, best: ["morning", "afternoon", "evening"], atmos: ["busy", "simple", "reliable"], acts: ["eat a dosa", "have a proper lunch"], land: ["indoor", "south indian"] },
  { id: "dadar-parsi", name: "Dadar's Parsi cafés", category: "restaurant", lat: 19.0200, lon: 72.8450, hood: "Dadar", dur: 50, price: 500, cap: 25, hours: "Mo-Su 10:00-22:00", stepFree: true, stroller: true, restroom: true, kid: true, indoor: "indoor", weather: "none", blurb: "Iranian Parsi cafes with patra ni machhi and berry pulao, in the one neighbourhood that still has them.", desc: "The Bombay Palli community concentrated in Dadar and Matunga, and the food follows. Cafés here have been going since the 1940s. A genuinely distinctive meal, and family-friendly.", kw: ["dadar", "parsi", "patra ni machhi", "salli", "berry pulao", "cafe", "family", "iranian"], rating: 4.5, count: 3100, best: ["afternoon", "evening"], atmos: ["old-school", "quiet", "generous"], acts: ["eat Parsi food", "try patra ni machhi"], land: ["indoor", "old cafe"] },
  { id: "sewri-koliwada", name: "Sewri Koliwada", category: "community_hosted", lat: 19.0000, lon: 72.8400, hood: "Sewri", dur: 50, price: 0, cap: null, hours: "Mo-Su 06:00-18:00", stepFree: true, stroller: false, restroom: false, kid: true, indoor: "outdoor", weather: "heat", blurb: "A Koli fishing village with working boats on the beach, and the city's most visible community.", desc: "The Koli are the original inhabitants of these islands and still fish from Sewri. Accessible, not staged, and worth handling with more care than a photogenic walk usually gets. Best early morning.", kw: ["koli", "sewri", "fishing village", "community", "boat", "early morning", "dharavi adjacent", "authentic"], rating: 4.2, count: 1700, best: ["early_morning", "morning"], atmos: ["working", "harsh", "authentic"], acts: ["see the fishing boats", "learn about the Koli"], land: ["outdoor", "coastal village"] },

  // ---- Bandra, Khar, Juhu
  { id: "bandra-fort", name: "Bandra Fort", category: "hidden_place", lat: 19.0470, lon: 72.8190, hood: "Bandra West", dur: 35, price: 0, cap: null, hours: "Mo-Su 07:00-20:00", stepFree: true, stroller: true, restroom: false, kid: true, indoor: "outdoor", weather: "any", blurb: "A Portuguese fort from 1617, with the only surviving camel stables in the city.", desc: "Later called Castella de Bandora, leased to Charles II of England in 1668. The camel stables and the causeway out to the sea are the parts people miss. Free, open, and off the beach by two streets.", kw: ["bandra fort", "portuguese", "camel stables", "ruins", "free", "hidden", "bandra", "history"], rating: 4.3, count: 5200, best: ["morning", "evening"], atmos: ["quiet", "ruinous", "cool breeze"], acts: ["climb the walls", "look at the stables", "see the causeway"], land: ["outdoor", "fort", "coastal"] },
  { id: "mount-mary-steps", name: "Mount Mary Steps", category: "hidden_place", lat: 19.0470, lon: 72.8200, hood: "Bandra West", dur: 25, price: 0, cap: null, hours: "24/7", stepFree: true, stroller: false, restroom: false, kid: false, indoor: "outdoor", weather: "any", blurb: "The blue-and-white steps from Mount Mary to the sea, lit at night.", desc: "Built for the Bandra Fair and now the best-known short walk in Bandra. The steps come out at the sea, the whole way is strollers-unfriendly and lamp-lit, and the sunset is the reason people climb.", kw: ["mount mary", "bandra", "steps", "sunset", "walk", "photogenic", "night", "free"], rating: 4.2, count: 6400, best: ["evening", "night"], atmos: ["photogenic", "breezy", "bittersweet"], acts: ["walk down the steps", "watch the sunset"], land: ["outdoor", "cliff steps", "sea"] },
  { id: "st-peters-bandra", name: "St. Peter's Church, Bandra", category: "church", lat: 19.0470, lon: 72.8210, hood: "Bandra West", dur: 25, price: 0, cap: null, hours: "Mo-Sa 06:00-20:00", stepFree: true, stroller: true, restroom: false, kid: true, indoor: "indoor", weather: "none", blurb: "A 1650s Portuguese church, free to enter, in the middle of Bandra's busiest junction.", desc: "Look for the two-headed eagle over the entrance. Dates from the Portuguese period and is the oldest thing in Bandra by a century. Free, cool inside, and strangely serene next to the junction.", kw: ["st peters", "bandra", "church", "portuguese", "free", "indoor", "old", "rain"], rating: 4.3, count: 4100, best: ["morning", "afternoon"], atmos: ["serene", "old", "cool"], acts: ["look at the eagle", "sit inside"], land: ["indoor church", "Portuguese era"] },
  { id: "kendeoka", name: "Kendeoka", category: "art_studio", lat: 19.0590, lon: 72.8410, hood: "Bandra West", dur: 75, price: 0, cap: 30, hours: "Tu-Sa 11:00-19:00", stepFree: true, stroller: true, restroom: true, kid: false, indoor: "indoor", weather: "none", blurb: "A printmaking and drawing studio in Pali Naka. Walk in and draw, and take the print home.", desc: "Multiple studios under one roof in central Bandra. A couple of hours of drawing with no experience needed, and you leave with something. The most reliably good rainy-morning plan in Bandra.", kw: ["kendeoka", "bandra", "art", "printmaking", "drawing", "workshop", "indoor", "rain", "class"], rating: 4.4, count: 2300, best: ["morning", "afternoon"], atmos: ["focused", "quiet", "creative"], acts: ["draw", "make a print", "learn something"], land: ["indoor", "artist studios"] },
  { id: "bKC-ranchi-paradise", name: "Ranchi House and BKC street food", category: "street_food", lat: 19.0620, lon: 72.8650, hood: "Bandra Kurla Complex", dur: 55, price: 350, cap: null, hours: "Mo-Su 12:00-23:30", stepFree: true, stroller: true, restroom: false, kid: true, indoor: "mixed", weather: "heat", blurb: "A legendary hole-in-the-wall for litti chokha in BKC, plus the office-worker crowd around it.", desc: "Litti chokha cooked in a coal oven, and the queue is a fair reflection of the quality. Lunch only in practice, even though the sign claims otherwise.", kw: ["ranchi house", "bKC", "litti chokha", "street food", "mahalaxmi", "bandra kurla", "cheaper"], rating: 4.3, count: 5600, best: ["afternoon"], atmos: ["chaotic", "beloved", "crowded"], acts: ["eat litti chokha", "join the queue"], land: ["outdoor stall", "office district"] },
  { id: "juhu-beach", name: "Juhu Beach", category: "beach", lat: 19.0750, lon: 72.8700, hood: "Juhu", dur: 60, price: 0, cap: null, hours: "24/7", stepFree: true, stroller: true, restroom: false, kid: true, indoor: "outdoor", weather: "any", blurb: "Wide, sandy, sunset-facing, and the reason Juhu exists. Not swimmable and nobody cares.", desc: "The sea here is not safe for swimming and the water is brown, but the sunset, the camel rides and the food stalls along the promenade are the point. Free.", kw: ["juhu", "beach", "sunset", "camel", "food stalls", "free", "family", "promenade"], rating: 4.1, count: 14200, best: ["evening"], atmos: ["breezy", "chaotic", "romantic"], acts: ["watch the sunset", "ride a camel", "eat off the stalls"], land: ["seafront", "outdoor", "wide"] },
  { id: "versova-koli", name: "Versova Koliwada", category: "community_hosted", lat: 19.1310, lon: 72.8090, hood: "Versova", dur: 50, price: 0, cap: null, hours: "Mo-Su 06:00-19:00", stepFree: true, stroller: false, restroom: false, kid: true, indoor: "outdoor", weather: "any", blurb: "The last Koli fishing village of central Mumbai, with boats landing in the afternoon.", desc: "Around 30 Koli families, the water buffalo on the beach, and the fishing boats coming in. The archer bows on the beach are the visual. Come mid-afternoon, not morning.", kw: ["versova", "koli", "fishing", "community", "boats", "archery", "afternoon", "versova village"], rating: 4.3, count: 1400, best: ["afternoon"], atmos: ["authentic", "working", "harsh"], acts: ["see the boats land", "watch the bows being made"], land: ["outdoor", "coastal village"] },
  { id: "seaside-link", name: "Worli Sea Link", category: "hidden_place", lat: 19.0270, lon: 72.8060, hood: "Worli", dur: 20, price: 0, cap: null, hours: "24/7", stepFree: true, stroller: true, restroom: false, kid: true, indoor: "outdoor", weather: "wind", blurb: "A cable-stayed bridge you can walk under for the best view of it.", desc: "Almost nobody walks the Worli Sea Link. Do it: the view back at the skyline from underneath is the reason, and it is thirty seconds of walking.", kw: ["worli sea link", "bridge", "skyline", "walk", "photogenic", "free", "mahalaxmi"], rating: 4.2, count: 3900, best: ["evening", "night"], atmos: ["impressive", "windy", "quiet"], acts: ["stand under the bridge", "photograph the skyline"], land: ["outdoor", "bridge", "sea"] },

  // ---- Dharavi and the community side
  { id: "dharavi-leather", name: "Dharavi leather workshops", category: "craft_workshop", lat: 19.0580, lon: 72.8530, hood: "Dharavi", dur: 60, price: 300, cap: 8, hours: "Mo-Sa 10:00-18:00", stepFree: true, stroller: true, restroom: false, kid: true, indoor: "indoor", weather: "none", blurb: "Leather working inside Dharavi's light industrial lanes. Book ahead; almost all of it is closed to walk-ins.", desc: "Real working workshops, not a shop. Leather bags, wallets, belts. A nominal fee goes to the artisan, and the interaction is the actual point. Children are welcome. Book at least a day ahead.", kw: ["dharavi", "leather", "workshop", "craft", "bag making", "book ahead", "indoor", "authentic", "family"], rating: 4.6, count: 1800, best: ["morning", "afternoon"], atmos: ["working", "hands-on", "hustling"], acts: ["make something", "learn a craft", "meet a maker"], land: ["indoor workshops", "working lanes"] },
  { id: "dharavi-women", name: "Women-led embroidery in Dharavi", category: "community_hosted", lat: 19.0575, lon: 72.8535, hood: "Dharavi", dur: 90, price: 250, cap: 6, hours: "Mo-Sa 10:00-17:00", stepFree: true, stroller: true, restroom: false, kid: false, indoor: "indoor", weather: "none", blurb: "A women-led embroidery collective. Booked through a local operator, and the money goes to them.", desc: "A small collective doing handwork and training women. Visit, sit with them, and understand what the tours that fly over Dharavi are missing. Book at least 48 hours ahead.", kw: ["dharavi", "embroidery", "women", "community", "social enterprise", "book ahead", "indoor"], rating: 4.7, count: 900, best: ["morning", "afternoon"], atmos: ["warm", "residential", "quiet"], acts: ["learn embroidery", "meet the makers"], land: ["indoor", "residential workshop"] },
  { id: "siddhivinayak", name: "Siddhivinayak Temple", category: "temple", lat: 19.0140, lon: 72.8350, hood: "Prabhadevi", dur: 45, price: 0, cap: null, hours: "Mo-Su 06:00-21:00", stepFree: true, stroller: true, restroom: true, kid: true, indoor: "covered", weather: "none", blurb: "Mumbai's most sought-after Ganesh temple, and a covered darshan in any weather.", desc: "The queues are real and the darshan is quick, and the whole complex is roofed, which makes it one of the few temples that works as a monsoon plan. Free. Modest dress, and remove leather belts.", kw: ["siddhivinayak", "ganesh", "temple", "darshan", "prabhadevi", "covered", "free", "rain", "family"], rating: 4.4, count: 16800, best: ["morning", "evening"], atmos: ["devotional", "crowded", "covered"], acts: ["darshan", "bless"], land: ["covered temple"] },
  { id: "chorbazaar", name: "Chor Bazaar", category: "market", lat: 19.0200, lon: 72.8450, hood: "Kalbadevi", dur: 70, price: 0, cap: null, hours: "Mo-Sa 10:00-19:00", stepFree: true, stroller: false, restroom: false, kid: true, indoor: "covered", weather: "any", blurb: "A 200-year-old market of antiques, brass, books and birds, under a roof. Covered, so it works in the rain.", desc: "Lingering market of importers and traders. Hard to navigate, easy to get lost in, and the birds section is genuinely memorable. Bargaining is expected and the opening price is fiction.", kw: ["chor bazaar", "kalbadevi", "market", "antiques", "birds", "covered", "bargaining", "rain"], rating: 4.2, count: 4900, best: ["morning", "afternoon"], atmos: ["dense", "bargaining", "covered"], acts: ["browse", "bargain", "get lost"], land: ["covered market", "old city"] },

  // ---- Powai, Chembur, BKC
  { id: "hiranandani", name: "Hiranandani Gardens", category: "hidden_place", lat: 19.1170, lon: 72.9020, hood: "Powai", dur: 50, price: 0, cap: null, hours: "Mo-Su 06:00-22:00", stepFree: true, stroller: true, restroom: true, kid: true, indoor: "outdoor", weather: "any", blurb: "A planned Hiranandani township built to feel like a European village, and it mostly does.", desc: "Butterfly gardens, a lake, and the Galleria shopping street. The contrast with the rest of the city is the curiosity. Best in the evening when the lights come on.", kw: ["hiranandani", "powai", "lake", "gardens", "planner township", "family", "evening", "free"], rating: 4.2, count: 6100, best: ["evening"], atmos: ["suburban", "green", "planned"], acts: ["walk the lake", "sit in the gardens"], land: ["outdoor", "lake", "planned township"] },
  { id: "chembur-sea", name: "Chembur Sea Link and the promenade", category: "hidden_place", lat: 19.0600, lon: 72.8900, hood: "Chembur", dur: 40, price: 0, cap: null, hours: "24/7", stepFree: true, stroller: true, restroom: false, kid: true, indoor: "outdoor", weather: "wind", blurb: "A sea link almost nobody uses, with a marine drive-style promenade under it.", desc: "Built for a road that mostly never arrived, so the Sea Link in Chembur is quiet and you can often walk on it. The promenade underneath has the same view as Marine Drive at a tenth of the footfall.", kw: ["chembur", "sea link", "promenade", "quiet", "walk", "free", "hidden", "sea"], rating: 4.1, count: 2100, best: ["evening", "morning"], atmos: ["quiet", "breezy", "lonely"], acts: ["walk the promenade", "look at the sea"], land: ["outdoor", "sea link", "promenade"] },
  { id: "iit-bombay", name: "IIT Bombay campus", category: "hidden_place", lat: 19.1240, lon: 72.9140, hood: "Powai", dur: 75, price: 0, cap: null, hours: "Mo-Sa 09:00-17:00", stepFree: true, stroller: true, restroom: true, kid: true, indoor: "mixed", weather: "any", blurb: "A walkable academic campus with a 19th-century Gothic tower and the best lake in the city.", desc: "Free to walk in with a photo ID at the gate. The Main Building tower, the old stone buildings, and the Powai lake path at the back. Genuinely surprising inside the city.", kw: ["iit", "powai", "campus", "gothic", "lake", "free", "walk", "id required"], rating: 4.4, count: 3800, best: ["morning", "afternoon"], atmos: ["green", "quiet", "spacious"], acts: ["walk the campus", "see the tower", "walk the lake"], land: ["outdoor campus", "gothic tower", "lake"] },

  // ---- Navi Mumbai
  { id: "cbd-belapur", name: "CBD Belapur", category: "hidden_place", lat: 19.1980, lon: 73.0300, hood: "Navi Mumbai", dur: 50, price: 0, cap: null, hours: "Mo-Su 07:00-21:00", stepFree: true, stroller: true, restroom: true, kid: true, indoor: "outdoor", weather: "any", blurb: "Navi Mumbai's planned centre, built around a lake and a hill. Almost no tourists.", desc: "A satellite city laid out on a grid in the 1980s, with a central lake, a Central Park, and a hill you can climb for the view back at the towers. Cheap, calm and completely unlike the island city.", kw: ["cbd belapur", "navi mumbai", "lake", "central park", "planned city", "free", "quiet", "family"], rating: 4.3, count: 2900, best: ["morning", "evening"], atmos: ["calm", "planned", "green"], acts: ["walk the lake", "climb the hill", "sit in the park"], land: ["outdoor", "planned city", "lake"] },
  { id: "global-pagoda", name: "Global Pagoda, Panvel", category: "hidden_place", lat: 19.0970, lon: 73.1200, hood: "Navi Mumbai", dur: 45, price: 0, cap: null, hours: "Mo-Su 07:00-18:30", stepFree: true, stroller: true, restroom: true, kid: true, indoor: "covered", weather: "any", blurb: "A 108-foot Buddhist stupa modelled on the one in Dharamshala, on a hill in Panvel.", desc: "A large white pagoda in a park, tall enough to see from the road. Free, a lift goes up, and the view over the hills to the east is the surprise.", kw: ["global pagoda", "panvel", "navi mumbai", "buddhist", "stupa", "hill", "free", "covered", "family"], rating: 4.2, count: 1900, best: ["morning", "afternoon"], atmos: ["spacious", "contemplative", "cool"], acts: ["climb the tower", "look at the view"], land: ["covered monument", "hilltop"] },
  { id: "kharghar-hill", name: "Kharghar Hill and the Central Park", category: "nature", lat: 19.0330, lon: 73.0700, hood: "Navi Mumbai", dur: 50, price: 0, cap: null, hours: "Mo-Su 06:00-19:00", stepFree: true, stroller: true, restroom: false, kid: true, indoor: "outdoor", weather: "heat", blurb: "A ridge with a 300 m climb and a view over the harbour, next to a big public park.", desc: "Kharghar is where you go in Navi Mumbai for a walk. The hill has a stepped path to the top, and the Central Park at the base is a proper large park. Free, and the opposite of the island city.", kw: ["kharghar", "navi mumbai", "hill", "park", "walk", "view", "free", "family", "central park"], rating: 4.2, count: 1600, best: ["early_morning", "morning"], atmos: ["green", "open", "quiet"], acts: ["climb the ridge", "walk the park"], land: ["outdoor", "ridge", "park"] },
  { id: "vashi-marina", name: "Seawoods Grand and Vashi waterfront", category: "hidden_place", lat: 19.0770, lon: 72.9970, hood: "Navi Mumbai", dur: 40, price: 0, cap: null, hours: "Mo-Su 07:00-21:00", stepFree: true, stroller: true, restroom: true, kid: true, indoor: "outdoor", weather: "wind", blurb: "A 23-acre seafront promenade in Seawoods, quiet and free, ten minutes from the ferry.", desc: "The Seawoods Grand is a long landscaped strip on the backwater with a lake, gardens, and benches. Free, and almost unused by visitors. Combined with the ferry from the island it makes a strong half-day.", kw: ["seawoods", "navi mumbai", "promenade", "backwater", "lake", "free", "family", "vashi"], rating: 4.1, count: 1100, best: ["evening", "morning"], atmos: ["calm", "green", "waterfront"], acts: ["walk the promenade", "sit by the water"], land: ["outdoor", "backwater", "promenade"] },
  { id: "sea-ferry", name: "Mumbai Sea Ferry, Wadala to Gatepier", category: "hidden_place", lat: 19.0300, lon: 72.9000, hood: "Wadala", dur: 35, price: 15, cap: null, hours: "Mo-Su 06:00-21:00", stepFree: true, stroller: true, restroom: false, kid: true, indoor: "outdoor", weather: "wind", blurb: "A commuter ferry across the harbour for Rs 15. Fifteen minutes, and the harbour views are better than the ones on land.", desc: "Fares in single digits, the crossing takes 12-15 minutes, and it skips the whole Dadar-Shimla junction. Suspended in heavy monsoon swell, which is worth knowing before you rely on it.", kw: ["ferry", "sea link", "harbour", "wadala", "gatepier", "cheap", "mumbai sea ferry", "view", "monsoon"], rating: 4.0, count: 2600, best: ["morning", "evening"], atmos: ["brisk", "breezy", "commuter"], acts: ["cross the harbour", "look at the skyline"], land: ["outdoor", "harbour crossing"] },

  // ---- Elephanta, the big day trip
  { id: "elephanta-caves", name: "Elephanta Caves", category: "heritage_site", lat: 18.8633, lon: 72.9133, hood: "Elephanta Island", dur: 180, price: 40, cap: null, hours: "Tu-Su 09:00-17:30", stepFree: false, stroller: false, restroom: true, kid: false, indoor: "covered", weather: "any", blurb: "Rock-cut cave temples from c. 550 CE, on an island in the harbour. Half a day and a boat ride.", desc: "UNESCO-listed, and the trip is the point: a 12-minute boat from the Gateway. Arrive by 10:00 or the boats stop running. The main cave is 6 steps up and the heat inside is significant. Closed Mondays.", kw: ["elephanta", "caves", "unesco", "boat", "day trip", "gharapuri", "cave temple", "tuesday to sunday", "hot"], rating: 4.5, count: 23400, best: ["morning"], atmos: ["ancient", "humid", "awe"], acts: ["take the boat", "see the Trimurti"], land: ["island", "cave", "heritage"] },

  // ---- Markets and shopping
  { id: "crawford-market", name: "Crawford Market", category: "market", lat: 19.0550, lon: 72.8390, hood: "Pali Hill", dur: 45, price: 0, cap: null, hours: "Mo-Su 10:00-20:00", stepFree: true, stroller: true, restroom: false, kid: true, indoor: "covered", weather: "none", blurb: "A Victorian market hall selling produce, imported cheese and, oddly, dogs. Covered, so it works in the rain.", desc: "Named after the Earl of Crawford, built in the 1860s, badly damaged in the 2001 riots and restored. The food side is genuinely good and the central aisle is a real produce market.", kw: ["crawford market", "pali hill", "market", "produce", "covered", "rain", "food", "victorian"], rating: 4.0, count: 5900, best: ["morning", "afternoon"], atmos: ["bustling", "covered", "tacky"], acts: ["browse produce", "eat"], land: ["covered market hall", "victorian"] },
  { id: "lower-parel-pheonix", name: "Phoenix Palladium of Mumbai", category: "shopping", lat: 19.0260, lon: 72.8310, hood: "Lower Parel", dur: 90, price: 0, cap: null, hours: "Mo-Su 11:00-22:00", stepFree: true, stroller: true, restroom: true, kid: true, indoor: "indoor", weather: "none", blurb: "A huge high-street mall. Not interesting, but it is a guaranteed 90-minute answer to rain with a toddler.", desc: "On the airport side, and enormous. Included deliberately: sometimes the right answer is a large air-conditioned building with a food court and a children's play area.", kw: ["lower parel", "phoenix", "mall", "indoor", "rain", "children", "play area", "family", "food court"], rating: 4.0, count: 18400, best: ["afternoon", "evening"], atmos: ["air-conditioned", "crowded", "neutral"], acts: ["escape the rain", "let kids play", "have a food court meal"], land: ["indoor mall"] },
  { id: "antiq-cola-bombay", name: "Antic, Kala Ghoda", category: "nightlife", lat: 18.9280, lon: 72.8330, hood: "Kala Ghoda", dur: 90, price: 1200, cap: 30, hours: "Tu-Su 19:00-01:00", stepFree: true, stroller: false, restroom: true, kid: false, indoor: "indoor", weather: "none", blurb: "A long bar in a 1906 building behind a 1935 art-deco facade. One of the better rooms in the city.", desc: "The building is doing most of the work. Two floors, good drinks list, and it opens at 19:00 which makes it an early option. Walkable from Colaba in ten minutes.", kw: ["antic", "kala ghoda", "bar", "cocktail", "evening", "night", "art deco", "colaba"], rating: 4.3, count: 1700, best: ["night", "evening"], atmos: ["dim", "civilised", "historic"], acts: ["have a drink", "see the building"], land: ["indoor bar", "art deco"] },

  // ---- Music and performance
  { id: "NCPA-bandwagon", name: "Experimental Band at NCPA", category: "music_live", lat: 18.9670, lon: 72.8230, hood: "Nariman Point", dur: 110, price: 400, cap: 400, hours: "Fr-Sa 18:00-21:00", stepFree: true, stroller: true, restroom: true, kid: false, indoor: "indoor", weather: "none", blurb: "A Friday-evening jazz and experimental programme at the National Centre for the Performing Arts.", desc: "The Tata Hall at NCPA, on the edge of Nariman Point by the Performing Arts Centre. Book ahead, because the Friday programme is the one people want. A genuinely good indoor evening.", kw: ["ncpa", "tata hall", "jazz", "music", "live", "nariman point", "friday", "indoor", "rain"], rating: 4.4, count: 900, best: ["evening", "night"], atmos: ["focused", "live", "adult"], acts: ["listen to live music"], land: ["indoor concert hall", "performing arts"] },
  { id: "national-centre-arts", name: "NCPA Experimental Series and the lawns", category: "theatre", lat: 18.9670, lon: 72.8230, hood: "Nariman Point", dur: 70, price: 0, cap: null, hours: "Mo-Su 08:00-21:00", stepFree: true, stroller: true, restroom: true, kid: true, indoor: "mixed", weather: "any", blurb: "Free theatre on the lawns, next to a working arts centre. A rare free thing of quality in the city.", desc: "The Godrej and Piramal lawns outside NCPA host free performances most weekends. Free entry, bring something to sit on, and check the schedule before you rely on it.", kw: ["ncpa", "theatre", "free", "lawns", "nariman point", "live", "weekend", "outdoor"], rating: 4.3, count: 1400, best: ["evening"], atmos: ["open-air", "cultural", "relaxed"], acts: ["watch free theatre", "sit on the lawns"], land: ["outdoor lawns", "performing arts"] },
  { id: "prithvi-theatre", name: "Prithvi Theatre, Juhu", category: "theatre", lat: 19.1230, lon: 72.8370, hood: "Juhu", dur: 130, price: 500, cap: 200, hours: "Mo-Su 19:00-23:00", stepFree: true, stroller: true, restroom: true, kid: false, indoor: "indoor", weather: "none", blurb: "An old bungalow theatre in Juhu, running Marathi and Hindi drama since 1977.", desc: "Gujarati and Marathi plays, a small house, and prices that have not moved in decades. Shows start at 19:30 and there is usually a long queue at the gate.", kw: ["prithvi", "theatre", "juhu", "marathi", "gujarati", "drama", "live", "evening", "indoor"], rating: 4.5, count: 1100, best: ["evening", "night"], atmos: ["intimate", "bustling", "local"], acts: ["watch a play"], land: ["indoor theatre", "bungalow"] },
  { id: "kathak-yerwada", name: "Kathak performance in the Fort precinct", category: "dance_performance", lat: 18.9360, lon: 72.8340, hood: "Fort", dur: 70, price: 300, cap: 60, hours: "We-Sa 19:00-20:30", stepFree: true, stroller: false, restroom: false, kid: false, indoor: "indoor", weather: "none", blurb: "Kathak and Bharatanatyam in the old Fort precinct, in a haveli.", desc: "Small-room classical performance, the kind that happens in Fort's restored havelis rather than a theatre. Book ahead; the groups are small and the audiences are mostly Indian.", kw: ["kathak", "bharatanatyam", "dance", "classical", "fort", "haveli", "evening", "indoor", "book ahead"], rating: 4.5, count: 380, best: ["evening"], atmos: ["intimate", "classical", "close"], acts: ["watch classical dance"], land: ["indoor haveli", "heritage"] },
  { id: "bhupen-khakhar", name: "Bhupen Khakhar Gallery", category: "gallery", lat: 18.9410, lon: 72.8230, hood: "Nariman Point", dur: 45, price: 0, cap: null, hours: "Tu-Sa 11:00-19:00", stepFree: true, stroller: true, restroom: false, kid: false, indoor: "indoor", weather: "none", blurb: "India's best-known living painter, in a converted bungalow on Malabar Hill.", desc: "Calm, serious, and a different register from the tourist galleries. The building is the philanthropist's house. Free and almost never crowded.", kw: ["bhupen khakhar", "gallery", "painting", "malabar hill", "nariman point", "free", "indoor", "art"], rating: 4.4, count: 1100, best: ["morning", "afternoon"], atmos: ["calm", "serious", "quiet"], acts: ["look at paintings", "have a quiet room"], land: ["indoor bungalow gallery"] },
  { id: "wellness-ghatkopar", name: "Ghatkopar and the rejuvenation circuit", category: "wellness", lat: 19.0890, lon: 72.9030, hood: "Ghatkopar", dur: 90, price: 1200, cap: 20, hours: "Mo-Su 08:00-21:00", stepFree: true, stroller: false, restroom: true, kid: false, indoor: "indoor", weather: "none", blurb: "For a day with a lot of walking in it, an Ayurvedic massage and a proper lunch is the reset.", desc: "A panchakarma clinic and a good vegetarian place near each other. Not a tourist attraction, and that is the appeal if your feet have opinions.", kw: ["ayurveda", "massage", "wellness", "ghatkopar", "panchakarma", "indian medicine", "indoor", "spa"], rating: 4.3, count: 700, best: ["afternoon"], atmos: ["quiet", "calm", "restorative"], acts: ["have a massage", "eat well"], land: ["indoor clinic"] },
  { id: "adventure-gateway", name: "Bike ride to the Kanheri caves approach", category: "adventure", lat: 19.2500, lon: 73.0900, hood: "Kanheri", dur: 240, price: 1500, cap: 8, hours: "Mo-Su 06:00-18:00", stepFree: true, stroller: true, restroom: true, kid: false, indoor: "mixed", weather: "heat", blurb: "A guided ride out of Mumbai to the Kanheri jungle, with the 108 cave complexes at the end.", desc: "A long day: the cave complex is worth it, but the 90-minute ride each way is a big part of what you are paying for. A Wednesday morning is near-empty. This is the one full-day option we would actually recommend.", kw: ["kanheri", "caves", "bike ride", "jungle", "adventure", "guided", "day trip", "wednesday", "long"], rating: 4.4, count: 520, best: ["morning"], atmos: ["green", "quiet", "adventurous"], acts: ["ride out", "see the caves", "get off-grid"], land: ["jungle", "caves", "outdoor"] },
  { id: "natasha-moshe-storm", name: "Monsoon boats from the Gateway", category: "adventure", lat: 18.9320, lon: 72.8347, hood: "Colaba", dur: 60, price: 900, cap: 8, hours: "Mo-Su 16:00-19:00", stepFree: true, stroller: true, restroom: false, kid: true, indoor: "outdoor", weather: "wind", blurb: "A small-boat trip out around the harbour in the late afternoon, when the city opens up.", desc: "A few operators run 5-6 person open boats from the Gateway jetty. The skyline from just offshore is the best free view of the city, and it is a different city in the rain. Cancelled in a proper squall, which is correct.", kw: ["boat", "harbour", "skyline", "colaba", "gateway", "afternoon", "view", "family", "monsoon"], rating: 4.3, count: 800, best: ["evening", "afternoon"], atmos: ["breezy", "cold", "exciting"], acts: ["get on a boat", "see the skyline from the water"], land: ["outdoor", "harbour"] },
  { id: "mumbai-film-city", name: "Film City tour", category: "hidden_place", lat: 19.1800, lon: 72.8800, hood: "Gorai", dur: 180, price: 900, cap: 20, hours: "Mo-Su 09:00-18:00", stepFree: true, stroller: true, restroom: true, kid: true, indoor: "mixed", weather: "heat", blurb: "The world's largest film studio complex, on the northern edge of the suburbs.", desc: "Set tours on a fixed timetable. The sets are genuinely the ones from the films, which is the entire appeal. Long drive each way, and hot. Not for a short window.", kw: ["film city", "studio", "bollywood", "gorai", "set tour", "day trip", "family", "kids"], rating: 4.1, count: 7300, best: ["morning"], atmos: ["huge", "hot", "set-piece"], acts: ["see film sets", "tour a studio"], land: ["studio sets", "outdoor and indoor"] },
];

// --- emit --------------------------------------------------------------------

const rand = seededRandom(seedFrom("mumbai", "seed", SEEDS.length));

interface Emitted {
  id: string;
  name: string;
  category: string;
  location: { lat: number; lon: number };
  durationMin: number;
  pricePerPerson: { minor: number; currency: string } | null;
  capacity: number | null;
  hours: { raw: string | null; status: string; lastVerified: string | null };
  indoorOutdoor: string;
  accessibility: Record<string, boolean | null>;
  kidFriendly: boolean | null;
  minAge: number | null;
  diets: string[];
  cuisines: string[];
  rating: { value: number; count: number; rawMean: number | null };
  blurb: string | null;
  description: string | null;
  keywords: string[];
  perception: { landscape: string[]; activities: string[]; atmosphere: string[] };
  bestTimeOfDay: string[];
  requiresJourney: boolean;
  booking: { required: boolean; leadTimeMin: number; walkIn: boolean };
  bestMonths: number[];
  weatherSensitive: string;
  provenance: Record<string, string>;
  providerId: string | null;
  neighbourhood: string;
  city: string;
}

  function toRow(s: Seed, _index: number): Emitted {
  // A little rating jitter so the Bayesian smoothing is exercised rather than
  // fed perfectly round numbers. Deterministic, so re-runs are identical.
  const jitter = Math.round((rand() - 0.5) * 12) / 100;
  const rawMean = Math.max(1, Math.min(5, Number((s.rating + jitter).toFixed(2))));

  const categories: Record<string, string[]> = {
    street_food: ["north indian", "chaat", "mughlai"],
    restaurant: ["north indian", "mughlai", "parsī", "iranian"],
    cafe: ["cafe", "italian", "continental"],
    market: ["vegetarian", "north indian"],
    temple: ["vegetarian"],
    mosque: ["vegetarian"],
  };

  const inferred: Record<string, string> = {
    durationMin: "inferred",
    pricePerPerson: "inferred",
    capacity: "inferred",
    kidFriendly: "inferred",
  };
  const curated: Record<string, string> = {
    name: "curated",
    category: "curated",
    location: "curated",
    hours: "curated",
    neighbourhood: "curated",
    blurb: "curated",
    description: "curated",
  };

  return {
    id: s.id,
    name: s.name,
    category: s.category,
    location: { lat: s.lat, lon: s.lon },
    durationMin: s.dur,
    pricePerPerson: s.price === 0 ? null : { minor: s.price * 100, currency: "INR" },
    capacity: s.cap,
    hours: { raw: s.hours, status: s.hours ? "ok" : "absent", lastVerified: null },
    indoorOutdoor: s.indoor,
    accessibility: {
      stepFree: s.stepFree,
      strollerOk: s.stroller,
      lowStairs: null,
      hearingLoop: null,
      seatingAvailable: null,
      restroomOnSite: s.restroom,
    },
    kidFriendly: s.kid,
    minAge: null,
    diets: s.category === "temple" || s.category === "mosque" ? ["vegetarian"] : [],
    cuisines: categories[s.category] ?? [],
    rating: { value: rawMean, count: s.count, rawMean },
    blurb: s.blurb,
    description: s.desc,
    keywords: s.kw,
    perception: { landscape: s.land, activities: s.acts, atmosphere: s.atmos },
    bestTimeOfDay: s.best,
    requiresJourney: s.category === "heritage_site" || s.category === "adventure",
    booking: s.book ?? { required: false, leadTimeMin: 0, walkIn: true },
    bestMonths: [],
    weatherSensitive: s.weather,
    provenance: { ...curated, ...inferred },
    providerId: null,
    neighbourhood: s.hood,
    city: "Mumbai",
  };
}

const rows = SEEDS.map(toRow);

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, rows.map((r) => JSON.stringify(r)).join("\n") + "\n", "utf8");

const byHood = new Map<string, number>();
for (const r of rows) byHood.set(r.neighbourhood, (byHood.get(r.neighbourhood) ?? 0) + 1);

console.log(`wrote ${rows.length} records -> ${OUT.replace(process.cwd() + "/", "")}`);
console.log(`neighbourhoods: ${byHood.size}`);
console.log(`with inferred duration: ${rows.filter((r) => r.provenance.durationMin === "inferred").length}`);
console.log(`free: ${rows.filter((r) => r.pricePerPerson === null).length}`);
console.log(`hours listed: ${rows.filter((r) => r.hours.raw !== null).length}`);
if (!existsSync(OUT)) process.exit(1);
