"use client";

/* ==========================================================================
   CROWD CANVAS — the moving people at the foot of the home page.

   A sprite-sheet crowd: one image is sliced into a grid, every cell gets its
   own tween walking it across the stage, and the crowd is depth-sorted by Y
   each frame so the figures nearest the bottom edge draw in front. Figures
   enter from alternating sides, recycle on completion, and bob on a yoyo while
   they walk, which is what makes a static bust read as a person moving.

   The artwork is generated by tools/generate-crowd-sheet.mjs and the grid is
   15 across by 7 down. Three things are load-bearing and easy to break:

   1. The vertical distribution is deliberately skewed. Random Y would centre
      the crowd; a power2.in ease against a large B pushes most figures DOWN,
      which is what hides the fact that these are busts with no legs and reads
      as a packed audience. A1/B1 are the skewed pair, A2/B2 the loose pair.

   2. Depth comes from sort order, not z-index. Peeps are sorted by anchorY
      and redrawn back-to-front every frame, because each figure is a separate
      drawImage with its own transform.

   3. The section sits at the very bottom of the page, so it is off-screen for
      most of a visit. 105 figures x 2 tweens is not free, so the loop only
      ticks while the section is on screen and the tab is visible. Without that
      this is a permanent battery cost for something nobody is looking at.
   ========================================================================== */

import { useEffect, useRef } from "react";
import { gsap } from "gsap";

const SHEET = "/crowd/peeps-sheet.svg";
const COLS_ACROSS = 15;
const ROWS_DOWN = 7;
const WALK_SECONDS = 10;
const BOB_SECONDS = 0.25;
const BOB_RISE = 10;

type Peep = {
  sx: number;
  sy: number;
  sw: number;
  sh: number;
  x: number;
  y: number;
  anchorY: number;
  scaleX: number;
  walk: gsap.core.Timeline | null;
};

type Box = { width: number; height: number };

/* Responsive scale for the figures themselves. */
function scaleFor(width: number) {
  if (width < 480) return 0.35;
  if (width < 960) return 0.5;
  return 1;
}

/* Vertical spread, as a fraction of a figure's own visible height rather than
   of the stage. Expressing it against the stage broke on narrow screens: a
   0.35-scaled figure is only ~90px tall, so stage-relative offsets pushed the
   whole mobile crowd into a thin strip along the bottom edge. Against the
   figure, one pair of numbers behaves the same at every breakpoint. */
const RISE_HIGH = 0.55; /* floats up to this far above the hem */
const RISE_RANGE = 1.15; /* and the skew span, biased low by power2.in */

const power2In = gsap.parseEase("power2.in");
const randomRange = (min: number, max: number) => min + Math.random() * (max - min);

function place(peep: Peep, stage: Box, scale: number) {
  const direction = Math.random() > 0.5 ? 1 : -1;
  const visibleH = peep.sh * scale;
  const offsetY =
    (RISE_HIGH - RISE_RANGE * power2In(Math.random())) * visibleH;
  const startY = stage.height - visibleH + offsetY;

  peep.scaleX = direction * scale;
  peep.x = direction === 1 ? -peep.sw * scale : stage.width + peep.sw * scale;
  peep.y = startY;
  peep.anchorY = startY;

  return { to: direction === 1 ? stage.width : 0, startY };
}

export default function CrowdCanvas() {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    let cancelled = false;
    const peeps: Peep[] = [];
    const stage: Box = { width: 0, height: 0 };
    let dpr = 1;
    let visible = true;
    let onScreen = false;
    let tickerFn: (() => void) | null = null;
    let observer: IntersectionObserver | null = null;

    const motionQuery = window.matchMedia("(prefers-reduced-motion: reduce)");
    const reduced = () => motionQuery.matches;

    const image = new Image();

    const draw = (peep: Peep) => {
      const scaleY = scaleFor(stage.width);
      ctx.save();
      ctx.translate(peep.x, peep.y);
      ctx.scale(peep.scaleX, scaleY);
      ctx.drawImage(image, peep.sx, peep.sy, peep.sw, peep.sh, 0, 0, peep.sw, peep.sh);
      ctx.restore();
    };

    const render = () => {
      if (!onScreen || !visible) return;
      ctx.setTransform(1, 0, 0, 1, 0, 0);
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      ctx.scale(dpr, dpr);
      /* Back to front: anchorY ascending means the highest figure is furthest
         away, so the dense low figures overlap it. */
      for (const peep of peeps) draw(peep);
    };

    const stopAll = () => {
      for (const peep of peeps) {
        peep.walk?.kill();
        peep.walk = null;
      }
    };

    /* Static layout for reduced motion: one evenly-spread row, no tweens. */
    const layoutStatic = () => {
      stopAll();
      const scale = scaleFor(stage.width);
      const step = (stage.width / peeps.length) * 1.4;
      let x = -step;
      for (const peep of peeps) {
        peep.x = x;
        peep.y = stage.height - peep.sh * scale * 0.92;
        peep.anchorY = peep.y;
        peep.scaleX = scale;
        x += step;
      }
      render();
    };

    const walk = (peep: Peep) => {
      const scale = scaleFor(stage.width);
      const { to, startY } = place(peep, stage, scale);
      /* Not paused. progress() below seeks, and an unpaused timeline keeps
         running from there — a paused one would place all 105 figures and then
         sit there forever. */
      const tl = gsap.timeline();
      tl.timeScale(randomRange(0.5, 1.5));
      tl.to(peep, { duration: WALK_SECONDS, x: to, ease: "none" }, 0);
      /* repeat is count-1 so the bob's total span lands on WALK_SECONDS and
         finishes with the walk rather than trailing a quarter-second behind. */
      tl.to(
        peep,
        {
          duration: BOB_SECONDS,
          repeat: WALK_SECONDS / BOB_SECONDS - 1,
          yoyo: true,
          y: startY - BOB_RISE,
        },
        0,
      );
      tl.eventCallback("onComplete", () => {
        if (cancelled) return;
        walk(peep);
      });
      /* A random starting progress is what stops 105 figures appearing to
         launch in unison on the first paint. */
      tl.progress(Math.random());
      peep.walk = tl;
    };

    const layout = () => {
      stage.width = canvas.clientWidth;
      stage.height = canvas.clientHeight;
      /* A zero-width stage means the section is not laid out yet (or is
         display:none). Laying out 105 walks against a 0px stage would put them
         all off-canvas and they would never recover on the next resize. */
      if (!stage.width || !stage.height) return;
      dpr = Math.min(window.devicePixelRatio || 1, 2);
      canvas.width = Math.round(stage.width * dpr);
      canvas.height = Math.round(stage.height * dpr);
      stopAll();
      if (reduced()) {
        layoutStatic();
        return;
      }
      for (const peep of peeps) walk(peep);
    };

    image.onload = () => {
      if (cancelled) return;
      const cellW = image.naturalWidth / COLS_ACROSS;
      const cellH = image.naturalHeight / ROWS_DOWN;
      for (let i = 0; i < COLS_ACROSS * ROWS_DOWN; i += 1) {
        peeps.push({
          sx: (i % COLS_ACROSS) * cellW,
          sy: ((i / COLS_ACROSS) | 0) * cellH,
          sw: cellW,
          sh: cellH,
          x: 0,
          y: 0,
          anchorY: 0,
          scaleX: 1,
          walk: null,
        });
      }
      layout();
      tickerFn = () => {
        peeps.sort((a, b) => a.anchorY - b.anchorY);
        render();
      };
      gsap.ticker.add(tickerFn);
    };
    /* The sheet is generated at build time; if it is missing the section is
       simply empty rather than a broken-image box. */
    image.onerror = () => undefined;
    image.src = SHEET;

    const resize = () => layout();
    window.addEventListener("resize", resize);

    const onVisibility = () => {
      visible = document.visibilityState === "visible";
    };
    document.addEventListener("visibilitychange", onVisibility);

    if ("IntersectionObserver" in window) {
      observer = new IntersectionObserver(
        (entries) => {
          onScreen = entries[0]?.isIntersecting ?? false;
          render();
        },
        { rootMargin: "120px" },
      );
      observer.observe(canvas);
    } else {
      onScreen = true;
    }

    const onMotionChange = () => layout();
    motionQuery.addEventListener("change", onMotionChange);

    return () => {
      cancelled = true;
      stopAll();
      if (tickerFn) gsap.ticker.remove(tickerFn);
      observer?.disconnect();
      window.removeEventListener("resize", resize);
      document.removeEventListener("visibilitychange", onVisibility);
      motionQuery.removeEventListener("change", onMotionChange);
    };
  }, []);

  return (
    <canvas
      ref={canvasRef}
      className="lal-crowd__canvas"
      /* The section below carries the text; the canvas is decoration. */
      aria-hidden="true"
    />
  );
}
