/**
 * Where things are, and how far apart they are.
 *
 * ---------------------------------------------------------------------------
 * THE COORDINATES ARE CITY CENTROIDS, AND THE PLANNER SAYS SO
 * ---------------------------------------------------------------------------
 *
 * The directory holds 892 places and not one latitude. `data/city-coords.json`
 * is 202 city centroids, generated by tools/gen-city-coords.mjs from the
 * GeoNames cities15000 dump: 186 resolved by matching the name and taking the
 * most populous match, and 16 hand-entered because that dump does not carry
 * them (nine are under 15,000 residents; seven are spelled differently there —
 * Köln, Gent, Wrocław). Those 16 are marked `"source": "manual"` in the file.
 *
 * So a stop dropped from the directory lands on its city's centre rather than
 * on the venue's front door, and the planner says so in the UI rather than
 * drawing a confident pin at the wrong place. This is the same trade the
 * directory itself already makes: `data/place-coords.ts` resolves `krakow` to
 * Kraków John Paul II *Airport*, which is a fine answer for a travel page and
 * a wrong one for a city a traveller is driving into.
 *
 * Upgrading to real per-venue points is a geocoding run over the 892 slugs, and
 * nothing else here would have to change: every consumer reads `coordsFor` or a
 * `Stop.at`, and neither knows where the number came from.
 */

import coordsData from "../../data/city-coords.json";
import type { LngLat } from "./types";

export type CityCoord = {
  name: string;
  lat: number;
  lon: number;
  country: string;
  population: number;
  /** "geonames" for the 186 looked up, "manual" for the 16 hand-entered. */
  source: "geonames" | "manual";
};

export const CITY_COORDS = coordsData as unknown as Record<string, CityCoord>;

/** Cities whose centroid was hand-entered rather than looked up. Counted at read
 *  time so the number in the UI cannot drift from the data. */
export const MANUAL_COORD_COUNT = Object.values(CITY_COORDS).filter(
  (c) => c.source === "manual",
).length;

export const CITY_COORD_COUNT = Object.keys(CITY_COORDS).length;

/** The centroid for a city slug, or null when the city is not in the file. */
export function coordsFor(city: string): CityCoord | null {
  if (!city) return null;
  return CITY_COORDS[city] ?? null;
}

/**
 * Where a stop sits.
 *
 * A directory place resolves through its city. A pin carries its own point and
 * has no city, which is the case that makes this a function rather than a
 * property lookup.
 */
export function pointForStop(stop: { at?: LngLat; city?: string }): LngLat | null {
  if (stop.at) return stop.at;
  const c = stop.city ? coordsFor(stop.city) : null;
  return c ? { lat: c.lat, lon: c.lon } : null;
}

/* -------------------------------------------------------------------------- *
 * Distance
 * -------------------------------------------------------------------------- */

const EARTH_RADIUS_KM = 6371;
const toRad = (deg: number) => (deg * Math.PI) / 180;

/** Great-circle distance in km. */
export function haversineKm(a: LngLat, b: LngLat): number {
  const dLat = toRad(b.lat - a.lat);
  const dLon = toRad(b.lon - a.lon);
  const lat1 = toRad(a.lat);
  const lat2 = toRad(b.lat);
  const h =
    Math.sin(dLat / 2) ** 2 + Math.sin(dLon / 2) ** 2 * Math.cos(lat1) * Math.cos(lat2);
  return 2 * EARTH_RADIUS_KM * Math.asin(Math.min(1, Math.sqrt(h)));
}

/**
 * Straight-line distance inflated to approximate a real journey.
 *
 * Only ever used when a leg could not be routed. The multipliers are the usual
 * road/track circuity figures and they are rough by design: the point of the
 * `Leg.basis` flag is that nobody has to trust this as a road distance.
 */
const CIRCUITY: Record<string, number> = { car: 1.3, bike: 1.4, foot: 1.2 };

/** Comfortable sustained speeds, used only for unroutable legs. */
const SPEED_KMH: Record<string, number> = { car: 80, bike: 16, foot: 4.5 };

export function estimateKm(a: LngLat, b: LngLat, mode: string): number {
  return haversineKm(a, b) * (CIRCUITY[mode] ?? CIRCUITY.car);
}

export function estimateHours(km: number, mode: string): number {
  return km / (SPEED_KMH[mode] ?? SPEED_KMH.car);
}

/* -------------------------------------------------------------------------- *
 * Geometry helpers
 * -------------------------------------------------------------------------- */

export function toLngLat(p: LngLat): [number, number] {
  return [p.lon, p.lat];
}

export function fromLngLat(c: [number, number]): LngLat {
  return { lon: c[0], lat: c[1] };
}

export type Bounds = { minLon: number; minLat: number; maxLon: number; maxLat: number };

/** The bounding box of a set of points, or null when there are none. */
export function boundsOf(points: readonly LngLat[]): Bounds | null {
  if (!points.length) return null;
  let minLon = Infinity;
  let minLat = Infinity;
  let maxLon = -Infinity;
  let maxLat = -Infinity;
  for (const p of points) {
    if (p.lon < minLon) minLon = p.lon;
    if (p.lat < minLat) minLat = p.lat;
    if (p.lon > maxLon) maxLon = p.lon;
    if (p.lat > maxLat) maxLat = p.lat;
  }
  return { minLon, minLat, maxLon, maxLat };
}

export function boundsCentre(b: Bounds): LngLat {
  return { lon: (b.minLon + b.maxLon) / 2, lat: (b.minLat + b.maxLat) / 2 };
}

/**
 * Shortest distance in km from a point to a polyline.
 *
 * This is what Furkot's "Spread" is measured against: how far a candidate place
 * sits from the route you have already built. Measured to the *segment* rather
 * than to the nearest vertex, because a route sampled every few kilometres would
 * otherwise report a candidate as far away when it is 200m off a straight run
 * between two of its own vertices.
 */
export function distanceToLineKm(p: LngLat, line: readonly [number, number][]): number {
  let best = Infinity;
  for (let i = 1; i < line.length; i++) {
    const d = distanceToSegmentKm(p, line[i - 1], line[i]);
    if (d < best) best = d;
  }
  return best;
}

const toXY = (p: [number, number], latRef: number) => {
  // Equirectangular about a fixed latitude. Over a single day's legs the
  // distortion is well under a percent, and it keeps the segment maths to four
  // multiplies instead of a projection library.
  const k = Math.cos(toRad(latRef));
  return { x: p[0] * k, y: p[1] };
};

function distanceToSegmentKm(p: LngLat, a: [number, number], b: [number, number]): number {
  const latRef = (a[1] + b[1]) / 2;
  const A = toXY(a, latRef);
  const B = toXY(b, latRef);
  const P = toXY([p.lon, p.lat], latRef);

  const dx = B.x - A.x;
  const dy = B.y - A.y;
  const lenSq = dx * dx + dy * dy;

  // A zero-length segment would divide by zero; its distance is the point distance.
  if (lenSq === 0) return haversineKm(p, fromLngLat(a));

  let t = ((P.x - A.x) * dx + (P.y - A.y) * dy) / lenSq;
  t = Math.max(0, Math.min(1, t));

  const proj: [number, number] = [A.x + t * dx, A.y + t * dy];
  // Undo the x-scaling before handing back to the haversine, which wants degrees.
  return haversineKm(p, { lon: proj[0] / Math.cos(toRad(latRef)), lat: proj[1] });
}

/** Metres per degree of longitude at a given latitude, for the map's scale bar. */
export function metresPerDegreeLon(lat: number): number {
  return 111_320 * Math.cos(toRad(lat));
}
